baseURL = "http://www.coachsauerfoundation.org/"
#baseURL = "https://usher-crab-54461.netlify.com/"
languageCode = "en-us"
title = "The Coach Sauer Foundation"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/coachsauerfoundation/"
  twitter = "https://twitter.com/coachsauerfndn"
  instagram = "https://www.instagram.com/coachsauerfoundation/"
  youtube = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  featured_image = "images/coach_and_camden.jpg"
  
[[menu.main]]
    name = "Events"
    url  = "/events"
    weight = 1
[[menu.main]]
    name = "Blog Posts"
    url  = "/post"
    weight = 2
[[menu.main]]
    name = "About US"
    url  = "/about"
    weight = 3
[[menu.main]]
    name = "Donate"
    url  = "/about/#donations"
    weight = 4
